
run-tests:
	@echo "Running tests..."
	forge test

run-script:
	@echo "Running script..."
	forge script script/DeployFundMe.s.sol

run-coverage:
	@echo "Running coverage..."
	forge coverage

PHONY: run-tests